# Generated by Django 3.1.3 on 2020-12-24 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_auto_20201224_0846'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_index=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment_content', models.CharField(max_length=200, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_card', to='card.card')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
