# Generated by Django 3.1.3 on 2020-12-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='comment_content',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
