# Generated by Django 3.1 on 2020-12-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20201231_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2020-12-31 12:55:24'),
        ),
    ]
