# Generated by Django 3.1 on 2020-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20201231_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2020-12-31 12:56:07'),
        ),
    ]
