# Generated by Django 3.1 on 2021-01-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_auto_20210107_0252'),
        ('activity', '0034_auto_20210106_1245'),
    ]

    operations = [
    ]
