# Generated by Django 3.1 on 2021-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_auto_20210107_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2021-01-07 05:17:58'),
        ),
    ]
