# Generated by Django 3.1 on 2021-01-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0041_auto_20210107_0517'),
        ('activity', '0041_merge_20210107_0459'),
    ]

    operations = [
    ]
