# Generated by Django 3.1 on 2021-01-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0043_auto_20210107_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
