# Generated by Django 3.1.3 on 2020-12-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('is_head', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_board', to='board.board')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_in', to='card.card')),
                ('prev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='list.list')),
            ],
        ),
    ]
