# Generated by Django 3.1.3 on 2020-12-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20201225_0812'),
        ('list', '0002_auto_20201225_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_in', to='card.card'),
        ),
        migrations.AlterField(
            model_name='list',
            name='prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='list.list'),
        ),
    ]
