# Generated by Django 3.1 on 2021-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20201225_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='prev',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='next', to='list.list'),
        ),
    ]
