# Generated by Django 3.1 on 2020-12-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '__first__'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_head', to='list.list'),
        ),
        migrations.AddField(
            model_name='board',
            name='key',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
