# Generated by Django 3.1 on 2020-12-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '__first__'),
        ('board', '0002_auto_20201223_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='head',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='board_head', to='list.list'),
            preserve_default=False,
        ),
    ]
