# Generated by Django 3.1 on 2021-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='userboard',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
