# Generated by Django 3.1.3 on 2020-12-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_head'),
        ('list', '0001_initial'),
        ('card', '0002_auto_20201224_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_board', to='board.board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_list', to='list.list'),
        ),
    ]
