# Generated by Django 3.1.3 on 2020-12-25 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0004_auto_20201225_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
