# Generated by Django 3.1 on 2021-01-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20210101_0236'),
        ('card', '0010_auto_20201231_1307'),
    ]

    operations = [
    ]
