# Generated by Django 3.1 on 2021-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_merge_20210104_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2021-01-04 15:02:58'),
        ),
        migrations.AlterField(
            model_name='card',
            name='prev',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='next', to='card.card'),
        ),
    ]
