# Generated by Django 3.1 on 2021-01-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_auto_20210105_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2021-01-05 02:56:09'),
        ),
    ]
