# Generated by Django 3.1 on 2021-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0046_merge_20210107_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2021-01-07 07:50:11'),
        ),
    ]
