# Generated by Django 3.1 on 2021-01-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0047_auto_20210107_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2021-01-08 23:12:07'),
        ),
    ]
