# Generated by Django 3.1 on 2021-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0049_auto_20210108_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2021-01-08 23:15:25'),
        ),
    ]
