# Generated by Django 3.1 on 2021-01-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0050_auto_20210108_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
